### PR TITLE
Fixing Some Mistakes

### PR DESCRIPTION
**Pull request by say25**
I know it doesn't matter a whole lot but....
1. I misspelled test 
2. I cased the cypher file differently so it sorted differently on Github.com

### CODE REVIEW

**Comment by say25** [comment]
@shiftkey you mind looking at this :/ my bad

**Comment by joshaber** [comment]
Should this also remove the existing Cypher file?

**Comment by say25** [comment]
Yea on my branch its gone :/ https://github.com/say25/highlighter-tests/tree/patch-1

**Comment by say25** [comment]
did a merge to make the diff better

**Comment by joshaber** [comment]
Looks great, thanks!

**Pull request merged**
